from src.controls.framework import ControlFramework, Control


def get_cobit_framework() -> ControlFramework:
    controls = [
        Control("EDM01", "Ensure Governance Framework", "Governance",
                "Establish and maintain a governance framework aligned with stakeholder needs"),
        Control("EDM02", "Ensure Benefits Delivery", "Governance",
                "Optimize value from IT-enabled investments and services"),
        Control("EDM03", "Ensure Risk Optimization", "Governance",
                "Ensure IT-related risk is managed within risk appetite"),
        Control("EDM04", "Ensure Resource Optimization", "Governance",
                "Ensure IT resources are optimized to meet organizational objectives"),
        Control("EDM05", "Ensure Stakeholder Transparency", "Governance",
                "Ensure transparent communication of IT performance and conformance"),
        Control("POB01", "Manage the IT Management Framework", "Management",
                "Establish and maintain an IT management framework"),
        Control("APO01", "Manage the IT Management Framework", "Management",
                "Define and maintain the IT management framework"),
        Control("APO02", "Manage Strategy", "Management",
                "Align IT strategy with business goals and objectives"),
        Control("APO03", "Manage Enterprise Architecture", "Management",
                "Establish and maintain enterprise architecture blueprint"),
        Control("APO04", "Manage Innovation", "Management",
                "Identify and evaluate emerging technologies for business innovation"),
        Control("APO07", "Manage Human Resources", "Management",
                "Manage IT personnel to ensure skilled and motivated workforce"),
        Control("APO08", "Manage Relationships", "Management",
                "Manage relationships between IT and business stakeholders"),
        Control("APO12", "Manage Risk", "Management",
                "Identify and manage IT-related business risks"),
        Control("APO13", "Manage Security", "Management",
                "Define and maintain information security management program"),
        Control("BAI01", "Manage Programs and Projects", "Management",
                "Manage IT programs and projects throughout their lifecycle"),
        Control("BAI03", "Manage Solutions Identification", "Management",
                "Identify and build IT solutions that meet business requirements"),
        Control("BAI06", "Manage IT Changes", "Management",
                "Manage all IT changes in a controlled manner"),
        Control("DSS01", "Manage Operations", "Management",
                "Manage and execute IT operational procedures"),
        Control("DSS02", "Manage Service Requests", "Management",
                "Manage and resolve service requests and incidents"),
        Control("DSS05", "Manage Security Services", "Management",
                "Protect information assets against security threats"),
        Control("MEA01", "Monitor Performance", "Management",
                "Monitor and evaluate IT performance against goals"),
        Control("MEA02", "Monitor Internal Control", "Management",
                "Monitor and evaluate internal control effectiveness"),
        Control("MEA03", "Monitor Regulatory Compliance", "Management",
                "Monitor and evaluate compliance with regulatory requirements"),
    ]
    return ControlFramework("COBIT", "2019", controls)
