from src.controls.framework import ControlFramework, Control


def get_iso27001_framework() -> ControlFramework:
    controls = [
        Control("A.5.1", "Information Security Policies", "Organizational",
                "Define and maintain information security policies"),
        Control("A.5.2", "Information Security Roles", "Organizational",
                "Assign information security roles and responsibilities"),
        Control("A.5.3", "Segregation of Duties", "Organizational",
                "Segregate conflicting duties to reduce risk"),
        Control("A.5.4", "Management Responsibilities", "Organizational",
                "Management to enforce information security through policy"),
        Control("A.5.5", "Contact with Authorities", "Organizational",
                "Maintain contacts with relevant regulatory authorities"),
        Control("A.5.6", "Contact with Special Interest Groups", "Organizational",
                "Participate in security information sharing groups"),
        Control("A.5.7", "Threat Intelligence", "Organizational",
                "Collect and analyze threat intelligence information"),
        Control("A.5.8", "Information Security in Project Management", "Organizational",
                "Integrate information security into project management"),
        Control("A.5.9", "Inventory of Information", "Organizational",
                "Maintain an inventory of information assets"),
        Control("A.5.10", "Acceptable Use", "Organizational",
                "Define acceptable use rules for information assets"),
        Control("A.6.1", "Screening", "People",
                "Conduct background verification checks on candidates"),
        Control("A.6.2", "Terms and Conditions", "People",
                "Include information security in employment terms"),
        Control("A.6.3", "Awareness and Training", "People",
                "Provide security awareness training to all personnel"),
        Control("A.6.4", "Disciplinary Process", "People",
                "Apply disciplinary process for security violations"),
        Control("A.6.5", "Post-employment Responsibilities", "People",
                "Manage security responsibilities after employment ends"),
        Control("A.7.1", "Physical Security Perimeter", "Physical",
                "Protect facilities with physical security perimeters"),
        Control("A.7.2", "Physical Entry Controls", "Physical",
                "Control physical access to secure areas"),
        Control("A.7.3", "Securing Offices and Rooms", "Physical",
                "Secure offices and rooms against unauthorized access"),
        Control("A.7.4", "Physical Security Monitoring", "Physical",
                "Monitor physical areas for unauthorized access"),
        Control("A.7.5", "Working in Secure Areas", "Physical",
                "Define procedures for working in secure areas"),
        Control("A.8.1", "User Endpoint Devices", "Technological",
                "Secure user endpoint devices"),
        Control("A.8.2", "Privileged Access Rights", "Technological",
                "Control allocation and use of privileged access rights"),
        Control("A.8.3", "Information Access Restriction", "Technological",
                "Restrict access to information based on need-to-know"),
        Control("A.8.4", "Access to Source Code", "Technological",
                "Control access to source code and development tools"),
        Control("A.8.5", "Secure Authentication", "Technological",
                "Implement secure authentication technologies"),
    ]
    return ControlFramework("ISO/IEC 27001", "2022", controls)
