from src.controls.framework import ControlFramework, Control


def get_nist_csf_framework() -> ControlFramework:
    controls = [
        Control("GV.OC-01", "Organizational Context", "GOVERN",
                "Understand organizational context including mission, stakeholder expectations, and legal/regulatory requirements"),
        Control("GV.RM-01", "Risk Management Strategy", "GOVERN",
                "Establish and communicate organizational risk management strategy"),
        Control("GV.RR-01", "Roles and Responsibilities", "GOVERN",
                "Define cybersecurity roles and responsibilities across the organization"),
        Control("GV.PO-01", "Policy Establishment", "GOVERN",
                "Establish and maintain cybersecurity policies"),
        Control("GV.OV-01", "Oversight", "GOVERN",
                "Provide oversight of cybersecurity risk management activities"),
        Control("ID.AM-01", "Asset Inventory", "IDENTIFY",
                "Maintain inventory of physical devices and systems"),
        Control("ID.AM-02", "Software Inventory", "IDENTIFY",
                "Maintain inventory of software platforms and applications"),
        Control("ID.AM-03", "Data Inventory", "IDENTIFY",
                "Maintain inventory of organizational data and data flows"),
        Control("ID.RA-01", "Risk Assessment", "IDENTIFY",
                "Identify and analyze cybersecurity risks to assets"),
        Control("ID.RA-02", "Threat Intelligence", "IDENTIFY",
                "Receive threat intelligence from information sharing forums"),
        Control("PR.AC-01", "Identity Management", "PROTECT",
                "Manage identities and credentials for authorized users"),
        Control("PR.AC-02", "Access Control", "PROTECT",
                "Control physical and logical access to assets"),
        Control("PR.DS-01", "Data at Rest Protection", "PROTECT",
                "Protect data-at-rest using encryption or equivalent controls"),
        Control("PR.DS-02", "Data in Transit Protection", "PROTECT",
                "Protect data-in-transit using encryption or equivalent controls"),
        Control("PR.AT-01", "Awareness and Training", "PROTECT",
                "Provide cybersecurity awareness and training to personnel"),
        Control("PR.PS-01", "Configuration Management", "PROTECT",
                "Establish and maintain configuration management practices"),
        Control("DE.CM-01", "Continuous Monitoring", "DETECT",
                "Monitor networks and systems for anomalous activity"),
        Control("DE.CM-02", "Log Collection", "DETECT",
                "Collect and correlate logs from diverse sources"),
        Control("DE.AE-01", "Event Analysis", "DETECT",
                "Analyze events to detect potential cybersecurity incidents"),
        Control("DE.DP-01", "Detection Processes", "DETECT",
                "Maintain detection processes and testing"),
        Control("RS.MA-01", "Incident Response Plan", "RESPOND",
                "Execute incident response plan when incidents occur"),
        Control("RS.CO-01", "Incident Communication", "RESPOND",
                "Communicate incident details to internal and external stakeholders"),
        Control("RS.MI-01", "Incident Mitigation", "RESPOND",
                "Contain and mitigate cybersecurity incidents"),
        Control("RS.IM-01", "Incident Improvement", "RESPOND",
                "Conduct post-incident reviews and improve processes"),
        Control("RC.RP-01", "Recovery Planning", "RECOVER",
                "Execute recovery plan to restore capabilities after incidents"),
        Control("RC.IM-01", "Recovery Improvement", "RECOVER",
                "Incorporate lessons learned into recovery planning"),
        Control("RC.CO-01", "Recovery Communication", "RECOVER",
                "Coordinate recovery activities with internal and external parties"),
    ]
    return ControlFramework("NIST Cybersecurity Framework", "2.0", controls)
