from src.controls.framework import ControlFramework, Control


def get_pci_dss_framework() -> ControlFramework:
    controls = [
        Control("1.1", "Firewall Configuration", "Build and Maintain a Secure Network",
                "Install and maintain firewall configuration standards"),
        Control("1.2", "Network Segmentation", "Build and Maintain a Secure Network",
                "Segment cardholder data environment from untrusted networks"),
        Control("1.3", "Prohibit Direct Access", "Build and Maintain a Secure Network",
                "Prohibit direct public access between internet and cardholder data"),
        Control("2.1", "Vendor Defaults", "Protect Cardholder Data",
                "Change vendor-supplied defaults for system passwords and security parameters"),
        Control("2.2", "Secure Configuration", "Protect Cardholder Data",
                "Develop and maintain secure configuration standards for systems"),
        Control("3.1", "Data Retention", "Protect Cardholder Data",
                "Limit cardholder data storage and retention to business needs"),
        Control("3.2", "Data Encryption", "Protect Cardholder Data",
                "Encrypt stored cardholder data using strong cryptography"),
        Control("4.1", "Encrypt Transmission", "Protect Cardholder Data",
                "Encrypt cardholder data transmitted over open public networks"),
        Control("5.1", "Anti-Malware", "Maintain Vulnerability Management Program",
                "Deploy and maintain anti-malware software on all systems"),
        Control("5.2", "Anti-Malware Updates", "Maintain Vulnerability Management Program",
                "Ensure anti-malware mechanisms are actively running and updated"),
        Control("6.1", "Secure Coding", "Maintain Vulnerability Management Program",
                "Develop and maintain secure coding standards"),
        Control("6.2", "Vulnerability Management", "Maintain Vulnerability Management Program",
                "Perform regular vulnerability scans and patch management"),
        Control("7.1", "Access Control", "Implement Strong Access Control Measures",
                "Restrict access to cardholder data by business need-to-know"),
        Control("7.2", "Access Management", "Implement Strong Access Control Measures",
                "Establish access control systems for cardholder data"),
        Control("8.1", "User Identification", "Implement Strong Access Control Measures",
                "Assign unique user IDs for all system access"),
        Control("8.2", "Strong Authentication", "Implement Strong Access Control Measures",
                "Implement multi-factor authentication for remote access"),
        Control("9.1", "Physical Security", "Regularly Monitor and Test Networks",
                "Control physical access to cardholder data environments"),
        Control("10.1", "Audit Logging", "Regularly Monitor and Test Networks",
                "Implement audit logging to track access to cardholder data"),
        Control("11.1", "Vulnerability Scans", "Regularly Monitor and Test Networks",
                "Perform regular internal and external vulnerability scans"),
        Control("12.1", "Information Security Policy", "Maintain an Information Security Policy",
                "Maintain a comprehensive information security policy"),
    ]
    return ControlFramework("PCI DSS", "v4.0", controls)
